# Generated by Django 4.2 on 2023-05-17 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(max_length=50, verbose_name='Класс')),
                ('stamina_points', models.IntegerField(verbose_name='Живучесть')),
                ('hit_points', models.IntegerField(verbose_name='Здоровье')),
                ('spell_class', models.TextField(blank=None, max_length=1000)),
                ('features_class', models.TextField(blank=None, max_length=1000)),
                ('key_characteristic', models.CharField(choices=[('strength', 'Сила'), ('dex', 'Ловкость'), ('con', 'Выносливость'), ('intelligence', 'Интелект'), ('wis', 'Мудрость'), ('cha', 'Харизма')], default='strength', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Сила')),
                ('dex', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Ловкость')),
                ('con', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Выносливость')),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Интелект')),
                ('wis', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Мудрость')),
                ('cha', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Харизма')),
                ('name_race', models.CharField(max_length=50, verbose_name='Класс')),
                ('hit_points', models.IntegerField(verbose_name='Здоровье')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('subtype', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Сила')),
                ('dex', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Ловкость')),
                ('con', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Выносливость')),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Интелект')),
                ('wis', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Мудрость')),
                ('cha', models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Харизма')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('hit_points', models.IntegerField(default=0, verbose_name='Здоровье')),
                ('strength_modifier', models.IntegerField(default=0, verbose_name='Модификатор силы')),
                ('dex_modifier', models.IntegerField(default=0, verbose_name='Модификатор ловкости')),
                ('con_modifier', models.IntegerField(default=0, verbose_name='Модификатор выносливости')),
                ('intelligence_modifier', models.IntegerField(default=0, verbose_name='Модификатор интелекта')),
                ('wis_modifier', models.IntegerField(default=0, verbose_name='Модификатор мудрости')),
                ('cha_modifier', models.IntegerField(default=0, verbose_name='Модификатор харизмы')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_as_class', to='Charlist.characterclass')),
                ('rase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_as_race', to='Charlist.race')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
