# Generated by Django 4.2.1 on 2023-05-19 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Интеллект'),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор интеллекта'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='key_characteristic',
            field=models.CharField(choices=[('strength', 'Сила'), ('dex', 'Ловкость'), ('con', 'Выносливость'), ('intelligence', 'Интеллект'), ('wis', 'Мудрость'), ('cha', 'Харизма')], default='strength', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='intelligence',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(26)], verbose_name='Интеллект'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name_race',
            field=models.CharField(max_length=50, verbose_name='Название расы'),
        ),
    ]
