# Generated by Django 4.2 on 2023-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hit_points',
            field=models.IntegerField(default=0, editable=False, verbose_name='Здоровье'),
        ),
    ]
