# Generated by Django 4.2 on 2023-05-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0002_alter_character_hit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_class',
            name='key_characteristic',
            field=models.CharField(choices=[('strength', 'Сила'), ('dex', 'Ловкость'), ('con', 'Выносливость'), ('intelligence', 'Интелект'), ('wis', 'Мудрость'), ('cha', 'Харизма')], default='strength', max_length=20),
        ),
    ]
