# Generated by Django 4.2 on 2023-05-03 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0003_character_class_key_characteristic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character_class',
            new_name='CharacterClass',
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points',
            field=models.IntegerField(default=0, verbose_name='Здоровье'),
        ),
        migrations.AlterField(
            model_name='race',
            name='cha',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Харизма'),
        ),
        migrations.AlterField(
            model_name='race',
            name='con',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Выносливость'),
        ),
        migrations.AlterField(
            model_name='race',
            name='dex',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Ловкость'),
        ),
        migrations.AlterField(
            model_name='race',
            name='intelligence',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Интелект'),
        ),
        migrations.AlterField(
            model_name='race',
            name='strength',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Сила'),
        ),
        migrations.AlterField(
            model_name='race',
            name='wis',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Мудрость'),
        ),
    ]
