# Generated by Django 4.2 on 2023-06-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0003_character_avatar_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
