# Generated by Django 4.2 on 2023-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0005_charactertheme_character_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='url',
            field=models.SlugField(default=None, max_length=130, unique=True),
        ),
    ]
