# Generated by Django 4.2 on 2023-06-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Charlist', '0006_character_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='url',
        ),
        migrations.AddField(
            model_name='character',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters_as_author', to='accounts.profile'),
        ),
    ]
