# Generated by Django 4.2 on 2023-06-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Charlist', '0007_remove_character_url_character_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characters_as_author', to='accounts.profile'),
        ),
    ]
