# Generated by Django 4.2 on 2023-06-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Charlist', '0008_alter_character_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characters_as_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
