# Generated by Django 4.2 on 2023-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0009_alter_character_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
