# Generated by Django 4.2 on 2023-07-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0010_character_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='slug',
        ),
    ]
