# Generated by Django 4.2 on 2023-07-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Charlist', '0011_remove_character_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_as_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
