# Generated by Django 4.2 on 2023-07-05 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0012_alter_character_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень оружия')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('damage', models.CharField(max_length=10, verbose_name='Урон')),
                ('crete', models.CharField(max_length=10, verbose_name='Крит')),
                ('features', models.CharField(max_length=10, verbose_name='Особые свойства')),
                ('distance', models.CharField(choices=[('near', 'Оружие ближнего боя'), ('further', 'Оружие дальнего боя')], default='near', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='cha_weapon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Charlist.weapon'),
        ),
    ]
