# Generated by Django 4.2 on 2023-07-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Charlist', '0013_weapon_character_cha_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cha_weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charlist.weapon'),
        ),
    ]
